---
commitizen:
  github_repo: apheris/cz_github_jira_conventional
  jira_base_url: https://myproject.atlassian.net
  jira_prefix: XX-
  name: cz_github_jira_conventional
  tag_format: v$version
  version: 3.0.1
